version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pictest
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 10
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    container_name: pic-nic-back
    depends_on:
        db:
          condition: service_healthy
    volumes: 
      - .:/app
      - /app/node_modules