version: '3'
services:
  nestjs:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    ports:
      - '4000:4000'
    container_name: pic-nic-back
    volumes:
      - .:/app
      - /app/node_modules
