version: '3'
services:
  postgresdb:
    platform: linux/x86_64
    image: postgres
    ports:
      - 5433:5432
    user: ${DB_USERNAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 20s
      retries: 10
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    container_name: pic-nic-back
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  database-data: {}
